create table product_category
(
    id       bigint generated by default as identity
        constraint product_category_pk
            primary key,
    category varchar(40) not null
);

alter table product_category
    owner to postgres;

insert into product_category (category)
values ('phone'),
       ('tv');

create table products
(
    id                  bigserial
        constraint products_pk
            primary key,
    name                varchar(50) not null,
    price               numeric     not null,
    product_category_id bigint      not null
        constraint products_product_category_id_fk
            references product_category
            on update cascade on delete cascade,
    info                varchar(150)
);

alter table products
    owner to postgres;

insert into products (name, price, product_category_id, info)
values ('Apple iphone 14', 999.99, 1, 'stylish ios phone'),
       ('Samsung S22', 799.99, 1, 'android  phone'),
       ('Xiaomi 13', 650, 1, 'android phone with miua'),
       ('Samsung S23', 950, 1, 'android flagman phone'),
       ('Xiaomi 13pro', 850, 1, 'global android phone with miua'),
       ('LG 55NAN', 459.99, 2, 'lg TV 55d'),
       ('LG 49S', 320, 2, 'lg TV 49d'),
       ('Sony KD-55', 540, 2, 'sony TV 55d');

create table users
(
    id       bigserial
        constraint users_pk
            primary key,
    login    varchar(30) not null,
    password varchar(30) not null,
    name     varchar(30) not null,
    surname  varchar(30) not null,
    email    varchar(50) not null
        constraint users_pk2
            unique,
    birthday date        not null
);

alter table users
    owner to postgres;

create table public.carts
(
    id         bigserial
        constraint carts_pk
            primary key,
    user_id    bigint            not null
        constraint carts_users_id_fk
            references public.users
            on update cascade on delete cascade,
    product_id bigint            not null
        constraint carts_products_id_fk
            references public.products
            on update cascade on delete cascade,
    cart       boolean,
    favorite   boolean,
    count      integer default 1 not null
);

alter table public.carts
    owner to postgres;

create table orders
(
    id      bigserial
        constraint orders_pk
            primary key,
    name    varchar(50) not null,
    date    date        not null,
    user_id integer     not null
        constraint orders_users_id_fk
            references users
            on update cascade on delete cascade
);

alter table orders
    owner to postgres;

create table order_product
(
    order_id   bigint not null
        constraint order_product_orders_id_fk
            references orders
            on update cascade on delete cascade,
    product_id bigint not null
        constraint order_product_products_id_fk
            references products
            on update cascade on delete cascade,
    constraint order_product_pk
        primary key (product_id, order_id)
);

alter table order_product
    owner to postgres;
